"""
PDF Generator for GeeksforGeeks Academic Scraper
Creates learning materials from scraped data
"""

import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from config import Config


class PDFGenerator:
    """Generates PDF learning materials"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()
        self.output_dir = Config.PDF_OUTPUT_DIR
        self.student_name = Config.STUDENT_NAME
        self.subject = Config.SUBJECT_CATEGORY
        os.makedirs(self.output_dir, exist_ok=True)
    
    def _setup_styles(self):
        """Set up PDF styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2E86C1'),
            alignment=TA_CENTER,
            spaceAfter=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#117A65'),
            spaceBefore=15,
            spaceAfter=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='BodyText',
            parent=self.styles['Normal'],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceBefore=5,
            spaceAfter=5
        ))
        
        self.styles.add(ParagraphStyle(
            name='CodeStyle',
            parent=self.styles['Normal'],
            fontSize=9,
            fontName='Courier',
            leftIndent=20,
            textColor=colors.HexColor('#1E8449')
        ))
    
    def _get_difficulty_color(self, difficulty):
        """Get color for difficulty badge"""
        colors_map = {
            'easy': colors.HexColor('#27AE60'),
            'medium': colors.HexColor('#F39C12'),
            'hard': colors.HexColor('#E74C3C')
        }
        return colors_map.get(difficulty.lower(), colors.HexColor('#95A5A6'))
    
    def generate_pdf(self, articles, filename=None):
        """Generate PDF from articles"""
        if not articles:
            return None
        
        if not filename:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"CSS_Learning_Module_{timestamp}.pdf"
        
        filepath = os.path.join(self.output_dir, filename)
        doc = SimpleDocTemplate(filepath, pagesize=A4)
        story = []
        
        # Title page
        story.append(Spacer(1, 2*inch))
        story.append(Paragraph("CSS Learning Module", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(f"Subject: {self.subject}", self.styles['Normal']))
        story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", self.styles['Normal']))
        story.append(Paragraph(f"Generated by: {self.student_name}", self.styles['Normal']))
        story.append(PageBreak())
        
        # Table of contents
        story.append(Paragraph("Table of Contents", self.styles['SectionHeading']))
        for i, article in enumerate(articles, 1):
            story.append(Paragraph(f"{i}. {article.get('title', 'Untitled')}", self.styles['BodyText']))
        story.append(PageBreak())
        
        # Articles
        for i, article in enumerate(articles, 1):
            # Title with difficulty badge
            title_text = f"{i}. {article.get('title', 'Untitled')}"
            story.append(Paragraph(title_text, self.styles['CustomTitle']))
            
            # Difficulty badge
            difficulty = article.get('difficulty', 'Not Available')
            badge_color = self._get_difficulty_color(difficulty)
            badge_data = [[Paragraph(f"Difficulty: {difficulty}", self.styles['Normal'])]]
            badge_table = Table(badge_data, colWidths=[2*inch])
            badge_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), badge_color),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('BOX', (0, 0), (-1, -1), 1, colors.black),
            ]))
            story.append(badge_table)
            story.append(Spacer(1, 0.2*inch))
            
            # Key Concepts
            story.append(Paragraph("Key Concepts", self.styles['SectionHeading']))
            story.append(Paragraph(article.get('concepts', 'Not Available'), self.styles['BodyText']))
            story.append(Spacer(1, 0.1*inch))
            
            # Code Snippets
            snippets = article.get('code_snippets', 'Not Available')
            if snippets != "Not Available" and snippets:
                story.append(Paragraph("Code Examples", self.styles['SectionHeading']))
                for j, snippet in enumerate(snippets, 1):
                    story.append(Paragraph(f"Example {j} ({snippet['language'].upper()}):", 
                                          self.styles['BodyText']))
                    story.append(Paragraph(snippet['code'], self.styles['CodeStyle']))
                    story.append(Spacer(1, 0.1*inch))
            
            # Complexity Analysis
            complexity = article.get('complexity', {})
            if complexity.get('time') != "Not Available" or complexity.get('space') != "Not Available":
                story.append(Paragraph("Complexity Analysis", self.styles['SectionHeading']))
                data = [
                    ["Time Complexity", "Space Complexity"],
                    [complexity.get('time', 'N/A'), complexity.get('space', 'N/A')]
                ]
                table = Table(data, colWidths=[3*inch, 3*inch])
                table.setStyle(TableStyle([
                    ('GRID', (0, 0), (-1, -1), 1, colors.black),
                    ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('PADDING', (0, 0), (-1, -1), 6),
                ]))
                story.append(table)
                story.append(Spacer(1, 0.1*inch))
            
            # References
            refs = article.get('references', 'Not Available')
            if refs != "Not Available" and refs:
                story.append(Paragraph("References", self.styles['SectionHeading']))
                for ref in refs[:3]:
                    story.append(Paragraph(f"• {ref.get('title', 'Link')}", self.styles['BodyText']))
            
            if i < len(articles):
                story.append(PageBreak())
        
        doc.build(story)
        return filepath
    
    def get_pdf_list(self):
        """Get list of generated PDFs"""
        if not os.path.exists(self.output_dir):
            return []
        
        pdfs = []
        for f in os.listdir(self.output_dir):
            if f.endswith('.pdf'):
                path = os.path.join(self.output_dir, f)
                pdfs.append({
                    'name': f,
                    'size': os.path.getsize(path),
                    'created': datetime.fromtimestamp(os.path.getctime(path)).strftime('%Y-%m-%d')
                })
        
        return sorted(pdfs, key=lambda x: x['created'], reverse=True)